def _dev(ctx):

  baseFolder = "{0}/concat.runfiles/{1}".format(ctx.executable.concat.dirname, ctx.workspace_name)

  es2105SourceFolder = "bazel-out/host/bin/{0}prod_source.es6/angular_samples".format(ctx.build_file_path.replace("BUILD.bazel", ""))
  sourceRoot = ctx.build_file_path.split("/")[0]

  args = ["--config", ""]
  args += ["rem1", ""]
  args += ["rem2", ""]
  args += ["--es6", es2105SourceFolder]
  args += ["--workspace", ctx.workspace_name]
  args += ["--sourceRoot", sourceRoot]
  args += ["--out1", ctx.outputs.bundle_es6_team0.path]


  print(ctx.build_file_path)

  ctx.action(
      executable = ctx.executable.concat,
      outputs = [
                 #ctx.outputs.bundle_es6_main, 
                 ctx.outputs.bundle_es6_team0,
                 #ctx.outputs.bundle_es6_team1,
                 #ctx.outputs.bundle_es6_team2,
                 #ctx.outputs.bundle_es6_team3,
                 #ctx.outputs.bundle_es6_team4,
                 #ctx.outputs.bundle_es6_team5,
                 #ctx.outputs.bundle_es6_team6,
                 #ctx.outputs.bundle_es6_team7,
                 #ctx.outputs.bundle_es6_team8,
                 #ctx.outputs.bundle_es6_team9,

                 #ctx.outputs.bundle_es6_chunk1,
                 #ctx.outputs.bundle_es6_chunk2
                 ],
      arguments = args
  )

  return struct()

dev = rule(
    implementation = _dev,
    attrs = {
        "concat": attr.label(default=Label("//src/apps/demo:concat"), executable=True, cfg="host", allow_files=True)
    },
    outputs = {
        #Chunks generated by Rollup
        #"bundle_es6_chunk1": "chunk1.js",
        #"bundle_es6_chunk2": "chunk2.js",

        #"bundle_es6_main": "main.js", 
        "bundle_es6_team0": "dev/team0.module.ngfactory.js",
        #"bundle_es6_team1": "team1.module.ngfactory.js",
        #"bundle_es6_team2": "team2.module.ngfactory.js",
        #"bundle_es6_team3": "team3.module.ngfactory.js",
        #"bundle_es6_team4": "team4.module.ngfactory.js",
        #"bundle_es6_team5": "team5.module.ngfactory.js",
        #"bundle_es6_team6": "team6.module.ngfactory.js",
        #"bundle_es6_team7": "team7.module.ngfactory.js",
        #"bundle_es6_team8": "team8.module.ngfactory.js",
        #"bundle_es6_team9": "team9.module.ngfactory.js"
    }
)