def _rollup(ctx):

  baseFolder = "{0}/rollup.runfiles/{1}".format(ctx.executable.rollup.dirname, ctx.workspace_name)
  rollupConfig = "{0}/rollup.config.js".format(baseFolder)

  es2105SourceFolder = "bazel-out/host/bin/{0}prod_source.es6".format(ctx.build_file_path.replace("BUILD.bazel", ""))
  sourceRoot = ctx.build_file_path.split("/")[0]

  args = ["--config", rollupConfig]
  args += ["--output.dir", ctx.outputs.bundle_es6_main.path.replace("main.js", "")]
  args += ["--output.format", "cjs"]
  args += ["--es6", es2105SourceFolder]
  args += ["--workspace", ctx.workspace_name]
  args += ["--sourceRoot", sourceRoot]


  print(ctx.build_file_path)

  ctx.action(
      executable = ctx.executable.rollup,
      outputs = [
                 ctx.outputs.bundle_es6_main, 
                 ctx.outputs.bundle_es6_team0,
                 ctx.outputs.bundle_es6_team1,
                 ctx.outputs.bundle_es6_team2,
                 ctx.outputs.bundle_es6_team3,
                 ctx.outputs.bundle_es6_team4,
                 ctx.outputs.bundle_es6_team5,
                 ctx.outputs.bundle_es6_team6,
                 ctx.outputs.bundle_es6_team7,
                 ctx.outputs.bundle_es6_team9,

                 ctx.outputs.bundle_es6_chunk1,
                # ctx.outputs.bundle_es6_chunk2
                 ],
      arguments = args
  )

  return struct()

rollup = rule(
    implementation = _rollup,
    attrs = {
        "rollup": attr.label(default=Label("//src/apps/demo:rollup"), executable=True, cfg="host", allow_files=True)
    },
    outputs = {
        #Chunks generated by Rollup
        "bundle_es6_chunk1": "chunk1.js",
        #"bundle_es6_chunk2": "chunk2.js",

        "bundle_es6_main": "main.js", 
        "bundle_es6_team0": "team0.module.ngfactory.js",
        "bundle_es6_team1": "team1.module.ngfactory.js",
        "bundle_es6_team2": "team2.module.ngfactory.js",
        "bundle_es6_team3": "team3.module.ngfactory.js",
        "bundle_es6_team4": "team4.module.ngfactory.js",
        "bundle_es6_team5": "team5.module.ngfactory.js",
        "bundle_es6_team6": "team6.module.ngfactory.js",
        "bundle_es6_team7": "team7.module.ngfactory.js",
        "bundle_es6_team9": "team9.module.ngfactory.js"
    }
)